DROP TABLE IF EXISTS order_product;
DROP TABLE IF EXISTS orders_date;
DROP TABLE IF EXISTS product_info;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS product;

CREATE TABLE product(
    id bigint generated by default as identity, 
    name varchar(255) not null, 
    picture_url varchar(255),
    price double precision not null,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE orders(
    id bigint generated by default as identity, 
    status varchar(255),
    date_created date default current_date not null,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE order_product(
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null,
    CONSTRAINT pk_order_product PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order_product_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_product_product FOREIGN KEY (product_id) REFERENCES product(id)
);