---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  DB_URI: "mongodb://{{ .Values.infra.mongodb.reports_user.username }}:{{ .Values.infra.mongodb.reports_user.password }}@mongodb:{{ .Values.infra.mongodb.containerPort }}/{{ .Values.infra.mongodb.reports_user.database }}?authSource={{ .Values.infra.mongodb.reports_user.database }}"